Repository cse110-sp21-group4/cse110-sp21-group4, pull requests merged in 2021-06, with the labels that each got.

#21 Right pane created
  .vscode/settings.json
  source/index.html
  source/js/main-page-controller.js
  source/js/script.js
  source/js/widgets/right-pane.js
  source/styles/calendar.css
Labels: enhancement, new feature

#23 Toolbar
  source/js/main-page-controller.js
  source/js/main.js
  source/js/script.js
  source/js/tests/main.test.js
  source/js/widgets/drag-view.js
  source/js/widgets/left-pane.js
  source/js/widgets/text-box.js
  source/js/widgets/toolbar.js
  source/styles/toolbar.css
Labels: new feature

#27 Controller tests
  source/js/main-page-controller.js
  source/js/tests/main-page-controller.test.js
  source/js/widgets/toolbar.js
Labels: enhancement

#29 Right pane - To-do list
  .vscode/settings.json
  source/js/widgets/right-pane.js
Labels: enhancement

#30 Data storage related features
  source/images/logo.png
  source/index.html
  source/js/main-page-controller.js
  source/js/main-page-model.js
  source/js/script.js
  source/js/tests/main-page-controller.test.js
  source/js/widgets/drag-view.js
  source/js/widgets/image-view.js
  source/js/widgets/left-pane.js
  source/js/widgets/right-pane.js
  source/js/widgets/text-box.js
  source/js/widgets/toolbar.js
  source/style.css
Labels: enhancement, new feature
