Repository cse110-sp21-group4/cse110-sp21-group4, pull requests merged in 2021-05, with the labels that each got.

#9 remove develop
  .github/workflows/build.yml
  .github/workflows/codacy-analysis.yml
Labels: documentation

#11 Controller
  .github/workflows/linter.yml
  source/build/js/bundle.js
  source/index.html
  source/js/main-page-controller.js
  source/js/script.js
Labels: enhancement

#13 Drag and drop view with bullet text
  source/index.html
  source/js/main-page-controller.js
  source/js/script.js
  source/js/widgets/drag-view.js
  source/js/widgets/image-view.js
  source/js/widgets/left-pane.js
  source/js/widgets/text-box.js
  source/style.css
  source/test.html
Labels: new feature

#8 add text on click
  docs/global.html
  docs/index.html
  docs/main.js.html
  source/index.html
  source/js/script.js
  source/js/widgets/drag-view.js
  source/style.css
Labels: enhancement
